### ISSUE TITLE
Anyone got this running with a Kamstrup Multical 302?

### ISSUE THREAD

**Issue by messismore** [bsdphk/PyKamstrup#4]
I have it hooked up to a Raspberry Pi with [this optical eye](http://shop.weidmann-elektronik.de/index.php?page=product&info=24), but all readings report `None`.

**Comment by JGaardDK** [comment]
Here are the Variables for Multical 302 (in decimal, convert to hex in code): 

ID Register Beskrivelse
1003 Date Aktuel dato (YYMMDD)
1002 Clock Aktuelt klokkeslæt (hhmmss)
99 InfoCode Infokode register, aktuelt
113 InfoEventCounter Infoeventtæller
1004 HourCounter Drifttimetæller
60 Energy1 Energiregister 1: Varmeenergi 
63 Energy3 Energiregister 3: Køleenergi
97 Energy8 Energiregister 8: [m3 x T1]
110 Energy9 Energiregister 9: [m3 x T2]
68 Volume1 Volumenregister V1
86 Temp1 Aktuel fremløbstemeratur
87 Temp2 Aktuel returløbstemeratur
89 Temp1-Temp2 Aktuel temperaturdifferens
74 Flow1 Aktuelt vandflow
80 Power1 Aktuel effekt
239 V1HighRes Højopløseligt volumenregister til testformål
266 E1HighRes Højopløseligt varmeenergiregister til testformål
267 E3HighRes Højopløseligt køleenergiregister til testformål
98 LogDaySetUp Skæringsdato (aflæsedato)
146 AvrTemp1(y) År til dato gennemsnit for T1
147 AvrTemp2(y) År til dato gennemsnit for T2
149 AvrTemp1(m) Måned til dato gennemsnit for T1
150 AvrTemp2(m) Måned til dato gennemsnit for T2
229 AutoIntT1Averrage T1 gennemsnit over sidste autointegration
230 AutoIntT2Averrage T2 gennemsnit over sidste autointegration
123 MaxFlow1Date(y) Dato for max. i indeværende år
124 MaxFlow1(y) Max. værdi i indeværende år
127 MaxPower1Date(y) Dato for max. i indeværende år
128 MaxPower1(y) Max. værdi i indeværende år
138 MaxFlow1Date(m) Dato for max. i indeværende måned
139 MaxFlow1(m) Max. værdi i indeværende måned
142 MaxPower1Date(m) Dato for max. i indeværende måned
143 MaxPower1(m) Max. værdi i indeværende måned
98 Xday Skæringsdato
153 ConfNo1 Konfig nr. ABDDD
168 ConfNo2 Konfig. nr. EFGHHMMM
1001 SerialNumber Serie nr. (unikt nummer for hver måler)
112 MeterNo(high) Kundenummer (8 mest betydende cifre)
1010 MeterNumber(low) Kundenummer (8 mindst betydende cifre)
1005 MeterType Målertype
184 MBusBotDispPriAddr Primær M-bus adresse
185 MBusBotDispSecAddr Sekundær M-bus adresse
154 CheckSum Software check-sum
175 Infohour Error hour counter

I found them in Tecnical documentation that I downloaded from here: https://products.kamstrup.com/index.php#
